name: Enhancement
description: Request a feature or suggest an idea for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: >
        Please check if there are already similar issues open!
        
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.

  - type: markdown
    attributes:
      value: >
        If you want to provide me with an additional incentive please take a look at my [commissions on Ko-fi](https://ko-fi.com/phoenix616/commissions).