blank_issues_enabled: false
contact_links:
  - name: "#moep IRC channel on irc.spi.gt"
    url: "https://kiwiirc.com/client/irc.spi.gt/#moep"
    about: My public IRC channel to discuss any of my projects
  - name: SpigotMC PM
    url: https://www.spigotmc.org/conversations/add?to=Phoenix616&title=Question
    about: Ask my questions privately
